// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
)

type Project struct {
	ID          string         `json:"id"`
	Slug        string         `json:"slug"`
	Name        string         `json:"name"`
	Color       sql.NullString `json:"color"`
	Archived    bool           `json:"archived"`
	CreatedAt   string         `json:"created_at"`
	UpdatedAt   string         `json:"updated_at"`
	DeletedAt   sql.NullString `json:"deleted_at"`
	SyncVersion sql.NullInt64  `json:"sync_version"`
}

type SyncState struct {
	Key   string         `json:"key"`
	Value sql.NullString `json:"value"`
}

type Task struct {
	ID          string         `json:"id"`
	ProjectID   string         `json:"project_id"`
	Content     string         `json:"content"`
	Status      sql.NullString `json:"status"`
	Priority    int            `json:"priority"`
	DueDate     sql.NullString `json:"due_date"`
	Tags        sql.NullString `json:"tags"`
	CreatedAt   string         `json:"created_at"`
	UpdatedAt   string         `json:"updated_at"`
	DeletedAt   sql.NullString `json:"deleted_at"`
	SyncVersion sql.NullInt64  `json:"sync_version"`
}
