// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"context"
	"database/sql"
)

type Querier interface {
	ClearProjects(ctx context.Context) error
	ClearTasks(ctx context.Context) error
	CountTasks(ctx context.Context, projectID string) (CountTasksRow, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) error
	CreateTask(ctx context.Context, arg CreateTaskParams) error
	DeleteProject(ctx context.Context, arg DeleteProjectParams) error
	DeleteTask(ctx context.Context, arg DeleteTaskParams) error
	GetProject(ctx context.Context, id string) (Project, error)
	GetTask(ctx context.Context, id string) (Task, error)
	GetTaskPartial(ctx context.Context, dollar_1 sql.NullString) (Task, error)
	ListProjects(ctx context.Context) ([]Project, error)
	ListTasks(ctx context.Context, arg ListTasksParams) ([]Task, error)
	MarkTaskDone(ctx context.Context, arg MarkTaskDoneParams) error
	UpdateTask(ctx context.Context, arg UpdateTaskParams) error
}

var _ Querier = (*Queries)(nil)
