// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package database

import (
	"context"
	"database/sql"
)

const clearProjects = `-- name: ClearProjects :exec
DELETE FROM projects
`

func (q *Queries) ClearProjects(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearProjects)
	return err
}

const clearTasks = `-- name: ClearTasks :exec
DELETE FROM tasks
`

func (q *Queries) ClearTasks(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearTasks)
	return err
}

const countTasks = `-- name: CountTasks :one
SELECT 
    COUNT(*) FILTER (WHERE done = 0),
    COUNT(*)
FROM tasks 
WHERE project_id = ? AND deleted_at IS NULL
`

type CountTasksRow struct {
	Count   int64 `json:"count"`
	Count_2 int64 `json:"count_2"`
}

func (q *Queries) CountTasks(ctx context.Context, projectID string) (CountTasksRow, error) {
	row := q.db.QueryRowContext(ctx, countTasks, projectID)
	var i CountTasksRow
	err := row.Scan(&i.Count, &i.Count_2)
	return i, err
}

const createProject = `-- name: CreateProject :exec
INSERT INTO projects (id, name, color, archived, created_at, updated_at, sync_version)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateProjectParams struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Color       sql.NullString `json:"color"`
	Archived    bool           `json:"archived"`
	CreatedAt   string         `json:"created_at"`
	UpdatedAt   string         `json:"updated_at"`
	SyncVersion sql.NullInt64  `json:"sync_version"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) error {
	_, err := q.db.ExecContext(ctx, createProject,
		arg.ID,
		arg.Name,
		arg.Color,
		arg.Archived,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.SyncVersion,
	)
	return err
}

const createTask = `-- name: CreateTask :exec
INSERT INTO tasks (id, project_id, content, done, priority, due_date, tags, created_at, updated_at, sync_version)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateTaskParams struct {
	ID          string         `json:"id"`
	ProjectID   string         `json:"project_id"`
	Content     string         `json:"content"`
	Done        bool           `json:"done"`
	Priority    int            `json:"priority"`
	DueDate     sql.NullString `json:"due_date"`
	Tags        sql.NullString `json:"tags"`
	CreatedAt   string         `json:"created_at"`
	UpdatedAt   string         `json:"updated_at"`
	SyncVersion sql.NullInt64  `json:"sync_version"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) error {
	_, err := q.db.ExecContext(ctx, createTask,
		arg.ID,
		arg.ProjectID,
		arg.Content,
		arg.Done,
		arg.Priority,
		arg.DueDate,
		arg.Tags,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.SyncVersion,
	)
	return err
}

const deleteProject = `-- name: DeleteProject :exec
UPDATE projects 
SET deleted_at = ?, updated_at = ?, sync_version = sync_version + 1
WHERE id = ?
`

type DeleteProjectParams struct {
	DeletedAt sql.NullString `json:"deleted_at"`
	UpdatedAt string         `json:"updated_at"`
	ID        string         `json:"id"`
}

func (q *Queries) DeleteProject(ctx context.Context, arg DeleteProjectParams) error {
	_, err := q.db.ExecContext(ctx, deleteProject, arg.DeletedAt, arg.UpdatedAt, arg.ID)
	return err
}

const deleteTask = `-- name: DeleteTask :exec
UPDATE tasks 
SET deleted_at = ?, updated_at = ?, sync_version = sync_version + 1
WHERE id = ?
`

type DeleteTaskParams struct {
	DeletedAt sql.NullString `json:"deleted_at"`
	UpdatedAt string         `json:"updated_at"`
	ID        string         `json:"id"`
}

func (q *Queries) DeleteTask(ctx context.Context, arg DeleteTaskParams) error {
	_, err := q.db.ExecContext(ctx, deleteTask, arg.DeletedAt, arg.UpdatedAt, arg.ID)
	return err
}

const getProject = `-- name: GetProject :one
SELECT id, name, color, archived, created_at, updated_at, deleted_at, sync_version FROM projects
WHERE id = ? AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetProject(ctx context.Context, id string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SyncVersion,
	)
	return i, err
}

const getTask = `-- name: GetTask :one
SELECT id, project_id, content, done, priority, due_date, tags, created_at, updated_at, deleted_at, sync_version FROM tasks
WHERE id = ? AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetTask(ctx context.Context, id string) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Content,
		&i.Done,
		&i.Priority,
		&i.DueDate,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SyncVersion,
	)
	return i, err
}

const getTaskPartial = `-- name: GetTaskPartial :one
SELECT id, project_id, content, done, priority, due_date, tags, created_at, updated_at, deleted_at, sync_version FROM tasks 
WHERE id LIKE ? || '%' AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetTaskPartial(ctx context.Context, dollar_1 sql.NullString) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTaskPartial, dollar_1)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Content,
		&i.Done,
		&i.Priority,
		&i.DueDate,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SyncVersion,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, name, color, archived, created_at, updated_at, deleted_at, sync_version FROM projects
WHERE deleted_at IS NULL
ORDER BY name
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.Archived,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.SyncVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasks = `-- name: ListTasks :many
SELECT id, project_id, content, done, priority, due_date, tags, created_at, updated_at, deleted_at, sync_version FROM tasks
WHERE deleted_at IS NULL
  AND (?1 IS NULL OR project_id = ?1)
  AND (?2 OR done = 0)
ORDER BY priority ASC, due_date ASC NULLS LAST, created_at DESC
`

type ListTasksParams struct {
	ProjectID   interface{} `json:"project_id"`
	IncludeDone interface{} `json:"include_done"`
}

func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasks, arg.ProjectID, arg.IncludeDone)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Content,
			&i.Done,
			&i.Priority,
			&i.DueDate,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.SyncVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTaskDone = `-- name: MarkTaskDone :exec
UPDATE tasks
SET done = ?, updated_at = ?, sync_version = sync_version + 1
WHERE id = ?
`

type MarkTaskDoneParams struct {
	Done      bool   `json:"done"`
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) MarkTaskDone(ctx context.Context, arg MarkTaskDoneParams) error {
	_, err := q.db.ExecContext(ctx, markTaskDone, arg.Done, arg.UpdatedAt, arg.ID)
	return err
}

const updateTask = `-- name: UpdateTask :exec
UPDATE tasks
SET project_id = ?, content = ?, done = ?, priority = ?, due_date = ?, tags = ?, updated_at = ?, sync_version = sync_version + 1
WHERE id = ?
`

type UpdateTaskParams struct {
	ProjectID string         `json:"project_id"`
	Content   string         `json:"content"`
	Done      bool           `json:"done"`
	Priority  int            `json:"priority"`
	DueDate   sql.NullString `json:"due_date"`
	Tags      sql.NullString `json:"tags"`
	UpdatedAt string         `json:"updated_at"`
	ID        string         `json:"id"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) error {
	_, err := q.db.ExecContext(ctx, updateTask,
		arg.ProjectID,
		arg.Content,
		arg.Done,
		arg.Priority,
		arg.DueDate,
		arg.Tags,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
