// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type IrontaskMagicLink struct {
	ID        uuid.UUID    `json:"id"`
	Email     string       `json:"email"`
	Token     string       `json:"token"`
	ExpiresAt time.Time    `json:"expires_at"`
	Used      sql.NullBool `json:"used"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type IrontaskProject struct {
	ID            uuid.UUID      `json:"id"`
	UserID        uuid.UUID      `json:"user_id"`
	ClientID      string         `json:"client_id"`
	Slug          string         `json:"slug"`
	Name          string         `json:"name"`
	Color         sql.NullString `json:"color"`
	EncryptedData []byte         `json:"encrypted_data"`
	SyncVersion   sql.NullInt64  `json:"sync_version"`
	Deleted       sql.NullBool   `json:"deleted"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
}

type IrontaskSession struct {
	ID        uuid.UUID    `json:"id"`
	UserID    uuid.UUID    `json:"user_id"`
	Token     string       `json:"token"`
	ExpiresAt time.Time    `json:"expires_at"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type IrontaskTask struct {
	ID               uuid.UUID      `json:"id"`
	UserID           uuid.UUID      `json:"user_id"`
	ClientID         string         `json:"client_id"`
	ProjectID        string         `json:"project_id"`
	EncryptedContent []byte         `json:"encrypted_content"`
	Status           sql.NullString `json:"status"`
	Priority         sql.NullInt32  `json:"priority"`
	DueDate          sql.NullString `json:"due_date"`
	SyncVersion      sql.NullInt64  `json:"sync_version"`
	Deleted          sql.NullBool   `json:"deleted"`
	CreatedAt        sql.NullTime   `json:"created_at"`
	UpdatedAt        sql.NullTime   `json:"updated_at"`
}

type IrontaskUser struct {
	ID           uuid.UUID    `json:"id"`
	Username     string       `json:"username"`
	Email        string       `json:"email"`
	PasswordHash string       `json:"password_hash"`
	CreatedAt    sql.NullTime `json:"created_at"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
}
