// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateSession(ctx context.Context, arg CreateSessionParams) (string, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteSession(ctx context.Context, token string) error
	GetProjectsChanged(ctx context.Context, arg GetProjectsChangedParams) ([]GetProjectsChangedRow, error)
	GetSession(ctx context.Context, token string) (GetSessionRow, error)
	GetTasksChanged(ctx context.Context, arg GetTasksChangedParams) ([]GetTasksChangedRow, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error)
	UpsertProject(ctx context.Context, arg UpsertProjectParams) error
	UpsertTask(ctx context.Context, arg UpsertTaskParams) error
}

var _ Querier = (*Queries)(nil)
